# Generated by Django 4.1.5 on 2023-02-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='short_info',
            new_name='description',
        ),
    ]
